<?php

use Illuminate\Database\Seeder;
use TCG\Voyager\Models\DataType;

class OrdersBreadRowAdded extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     *
     * @throws Exception
     */
    public function run()
    {
        try {
            \DB::beginTransaction();

            $dataType = DataType::where('name', 'orders')->first();

            \DB::table('data_rows')->insert(array(
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'id',
                    'type' => 'text',
                    'display_name' => 'Id',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => json_encode([]),
                    'order' => 1,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'name',
                    'type' => 'text',
                    'display_name' => 'Name',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 9,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'email',
                    'type' => 'text',
                    'display_name' => 'Email',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 10,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'phone',
                    'type' => 'text',
                    'display_name' => 'Phone',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 11,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'payment_method',
                    'type' => 'text',
                    'display_name' => 'Payment Method',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 12,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'transaction_id',
                    'type' => 'text',
                    'display_name' => 'Transaction Id',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => json_encode([]),
                    'order' => 13,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'cc_number',
                    'type' => 'text',
                    'display_name' => 'Cc Number',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 14,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'cc_name',
                    'type' => 'text',
                    'display_name' => 'Cc Name',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 15,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'cc_expiration',
                    'type' => 'text',
                    'display_name' => 'Cc Expiration',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 16,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'cc_expiration_month',
                    'type' => 'text',
                    'display_name' => 'Cc Expiration Month',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 17,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'cc_expiration_year',
                    'type' => 'text',
                    'display_name' => 'Cc Expiration Year',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 18,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'cc_cvv',
                    'type' => 'text',
                    'display_name' => 'Cc Cvv',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 19,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'card_type',
                    'type' => 'text',
                    'display_name' => 'Card Type',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 20,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'gclid',
                    'type' => 'text',
                    'display_name' => 'Gclid',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 21,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'tax_rate',
                    'type' => 'text',
                    'display_name' => 'Tax Rate',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 22,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'tax',
                    'type' => 'text',
                    'display_name' => 'Tax',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 23,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'shipping_cost',
                    'type' => 'text',
                    'display_name' => 'Shipping Cost',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 24,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'subtotal',
                    'type' => 'text',
                    'display_name' => 'Subtotal',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 25,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'total',
                    'type' => 'text',
                    'display_name' => 'Total',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 26,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'confirmed',
                    'type' => 'text',
                    'display_name' => 'Confirmed',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 27,
                ),
                array(
                    'data_type_id' => $dataType->id,
                    'field' => 'confirmed_at',
                    'type' => 'timestamp',
                    'display_name' => 'Confirmed At',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 1,
                    'details' => json_encode([]),
                    'order' => 28,
                )
            ));
        } catch (Exception $e) {
            throw new Exception('exception occur ' . $e);

            \DB::rollBack();
        }

        \DB::commit();
    }
}
